Bugfixes for two crashes appearing during reply parsing of repository_create (output of this command is different from normal status, unfortunately). The latter appeared after I fixed the former.
Wrong parsing of username
---------------------------

Username returned from repository_create is plain text, not structure.
So the code crashed with:

    Traceback (most recent call last):
      File "/home/marcink/.local/lib/python2.7/site-packages/pybitbucket/repository.py", line 139, in create_repository
        return Repository(response.json(), client=client)
      File "/home/marcink/.local/lib/python2.7/site-packages/pybitbucket/repository.py", line 57, in __init__
        self.owner = User(data['owner'], client=client)
      File "/home/marcink/.local/lib/python2.7/site-packages/pybitbucket/bitbucket.py", line 111, in __init__
        in data.items()}
    AttributeError: 'unicode' object has no attribute 'items'

I fixed that by detecting that case and making tiny user-like structure
out of it.

Bad handling of missing links
--------------------------------

Once I started returning this structure, I got:

    Traceback (most recent call last):
      File "/home/marcink/DEV_hg/python/bitbucket/pybitbucket/repository.py", line 146, in create_repository
        return Repository(response.json(), client=client)
      File "/home/marcink/DEV_hg/python/bitbucket/pybitbucket/repository.py", line 65, in __init__
        if data.get('links').get('clone'):
    AttributeError: 'NoneType' object has no attribute 'get'

As using .get showed intent to keep working in case block is missing, I fixed
it appropriately, so the line above yielded None instead of crashing.